import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("text-base antialiased", inter.className)}>
        <ClerkProvider>
          <Providers>
            {children}
            <div className="isolate"></div>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
